export const SET_PRIMARY_CURRENCY = "SET_PRIMARY_CURRENCY";
export const SET_SECONDARY_CURRENCY = "SET_SECONDARY_CURRENCY";
export const SET_AMOUNT = "SET_AMOUNT";
export const SET_IS_LOADING = "SET_IS_LOADING ";
export const SET_CURRENCY_HISTORY = "SET_CURRENCY_HISTORY ";
